-- Création de la classe de Cécile (généré depuis docsmethodes/).
do $$
declare
  v_user uuid;
  v_class uuid;
begin
  select id into v_user from auth.users where email = 'azylis69@hotmail.fr';
  if v_user is null then raise exception 'Utilisateur % introuvable', 'azylis69@hotmail.fr'; end if;

  -- Non destructif : on n'écrit QUE si aucune classe n'existe encore pour ce compte.
  if exists (select 1 from classes where user_id = v_user) then
    raise notice 'Une classe existe deja pour ce compte : aucune insertion.';
    return;
  end if;

  insert into classes (user_id, manuel_id, rentree_date, prenom_enseignant)
    values (v_user, 'custom', '2026-09-01', 'Cécile')
    returning id into v_class;

  -- ── semaines (36) ──
  insert into semaines (class_id, numero, date_debut, graphemes, edm_theme, edm_competences, manuel_pages, mots_exemple, note) values
    (v_class, 1, ('2026-09-01'::date + 0), array['a','i','y','o','u'], 'Moi', 'Identifier les parties du corps. Se repérer dans l''espace proche.', '8-9', null, null),
    (v_class, 2, ('2026-09-01'::date + 7), array['e','é','l'], 'Moi', 'Utiliser ses sens pour explorer son environnement.', '10-11', array['lit'], null),
    (v_class, 3, ('2026-09-01'::date + 14), array['r','f'], 'L''école', 'Se repérer dans un espace connu. Lire un plan simple.', '12-13', array['rat','fée'], null),
    (v_class, 4, ('2026-09-01'::date + 21), array['j','ou'], 'Le temps', 'Ordonner des événements. Utiliser un calendrier de classe.', '14-15', array['jars','loup'], null),
    (v_class, 5, ('2026-09-01'::date + 28), array['v','ch'], 'Le temps', 'Reconnaître les saisons. Observer les changements dans la nature.', '18-19', array['vol','chat'], null),
    (v_class, 6, ('2026-09-01'::date + 35), array['e','s','t','h'], 'Le vivant', 'Distinguer animaux sauvages et domestiques. Décrire leurs caractéristiques.', '20-25', array['lettres muettes'], null),
    (v_class, 7, ('2026-09-01'::date + 42), array['p','t'], 'Le vivant', 'Observer la germination. Comprendre les besoins d''une plante.', '26-27', array['poule','tomate'], null),
    (v_class, 8, ('2026-09-01'::date + 49), array['b','d'], 'La matière', 'Identifier les matériaux (bois, métal, plastique). Classer des objets.', '28-29', array['balle','doudou'], null),
    (v_class, 9, ('2026-09-01'::date + 56), array['m','n'], 'La matière', 'Observer les états de l''eau (solide, liquide). Faire des expériences simples.', '32-33', array['mouche','nid'], null),
    (v_class, 10, ('2026-09-01'::date + 63), array['z','s'], 'La société', 'Décrire sa famille. Comprendre les liens familiaux.', '34-35', array['zoo','souris'], null),
    (v_class, 11, ('2026-09-01'::date + 70), array['s','è','ê'], 'La société', 'Comprendre l''importance des règles. Distinguer droits et devoirs.', '38-39', array['rose','sirène'], null),
    (v_class, 12, ('2026-09-01'::date + 77), array['es','eu','œu'], 'L''espace', 'Se repérer dans l''espace local. Utiliser des repères spatiaux.', '40-41', array['les','jeu','œuf'], null),
    (v_class, 13, ('2026-09-01'::date + 84), array['a','d'], 'Le vivant', 'Découvrir l''hibernation. Observer l''adaptation des animaux aux saisons.', '42-47', array['lettres muettes'], null),
    (v_class, 14, ('2026-09-01'::date + 91), array['c','k'], 'Le temps', 'Situer des événements dans le temps. Utiliser un axe chronologique simple.', '48-49', array['canard','kimono'], null),
    (v_class, 15, ('2026-09-01'::date + 98), array['q','qu','g','gu'], 'La matière', 'Observer la formation des ombres. Comprendre que la lumière se propage en ligne droite.', '50-51', array['coq','queue','goutte','guitare'], null),
    (v_class, 16, ('2026-09-01'::date + 105), array['an','am','en','em'], 'Le vivant', 'Identifier les aliments. Comprendre l''équilibre alimentaire.', '54-55', array['maman','vent'], null),
    (v_class, 17, ('2026-09-01'::date + 112), array['on','om','in','im'], 'La société', 'Découvrir différents métiers. Comprendre la notion de travail.', '56-57', array['mouton','poussin'], null),
    (v_class, 18, ('2026-09-01'::date + 119), array['oi','oin'], 'Le vivant', 'Comprendre les gestes d''hygiène. Connaître les règles de sécurité simples.', '60-61', array['étoile','point'], null),
    (v_class, 19, ('2026-09-01'::date + 126), array['au','eau'], 'Le temps', 'Observer les caractéristiques de l''hiver. Comparer les saisons.', '62-63', array['taupe','oiseau'], null),
    (v_class, 20, ('2026-09-01'::date + 133), array['b','f','c'], 'L''espace', 'Identifier différents types de paysages (mer, montagne, plaine). Localiser sur une carte simple.', '64-69', array['lettres muettes'], null),
    (v_class, 21, ('2026-09-01'::date + 140), array['ai','ei','err','ess','ett','eil','enn'], 'La société', 'Découvrir les différents moyens de transport. Comprendre leur utilité.', '70-71', array['laine','reine','terre'], null),
    (v_class, 22, ('2026-09-01'::date + 147), array['e','et'], 'Le vivant', 'Observer la croissance des plantes. Comprendre la photosynthèse de manière simple.', '73-74', array['mer','poulet'], null),
    (v_class, 23, ('2026-09-01'::date + 154), array['er','ez','ph'], 'Le temps', 'Observer les changements du printemps. Reconnaître les plantes qui fleurissent.', '78-79', array['rocher','nez','phoque'], null),
    (v_class, 24, ('2026-09-01'::date + 161), array['c','ç','sc'], 'La matière', 'Distinguer mélanges homogènes et hétérogènes. Réaliser des expériences simples.', '81-82', array['glace','garçon','piscine'], null),
    (v_class, 25, ('2026-09-01'::date + 168), array['g','ge'], 'La société', 'Découvrir les institutions de base. Comprendre les règles de la vie en commun.', '86-87', array['girafe','pigeon'], null),
    (v_class, 26, ('2026-09-01'::date + 175), array['gn','ain','ein'], 'L''espace', 'Situer la France en Europe. Découvrir quelques pays voisins.', '89-90', array['cigogne','copain','peinture'], null),
    (v_class, 27, ('2026-09-01'::date + 182), array['g','l','p'], 'Le vivant', 'Comprendre le cycle de vie d''un animal (oeuf → adulte). Observer des métamorphoses.', '92-97', array['lettres muettes'], null),
    (v_class, 28, ('2026-09-01'::date + 189), array['ier','ieu','ion','ian','ien'], 'La matière', 'Identifier des outils et machines simples. Comprendre leur fonctionnement de base.', '98-99', array['cahier','chien'], null),
    (v_class, 29, ('2026-09-01'::date + 196), array['x','ti'], 'Le temps', 'Comprendre que le passé laisse des traces. Observer des documents anciens.', '104-105', array['xylophone','addition'], null),
    (v_class, 30, ('2026-09-01'::date + 203), array['y','ay','oy','ey','uy'], 'L''espace', 'Comparer la ville et la campagne. Identifier les activités humaines selon les espaces.', '112-113', array['yaourt','crayon'], null),
    (v_class, 31, ('2026-09-01'::date + 210), array['ill','ail','eil','euil','ouil'], 'Le vivant', 'Comprendre l''importance de protéger l''environnement. Découvrir les gestes éco-responsables.', '118-119', array['coquille','soleil'], null),
    (v_class, 32, ('2026-09-01'::date + 217), array['w'], 'Le temps', 'Reconnaître les caractéristiques de l''été. Faire le bilan des 4 saisons.', '126-127', array['kiwi'], null),
    (v_class, 33, ('2026-09-01'::date + 224), '{}'::text[], 'La société', 'Découvrir les fêtes du calendrier. Comprendre les traditions culturelles.', '132-135', array['cas particuliers'], null),
    (v_class, 34, ('2026-09-01'::date + 231), '{}'::text[], 'La matière', 'Comprendre que l''air existe et a des propriétés. Faire des expériences avec l''air.', null, array['révision'], null),
    (v_class, 35, ('2026-09-01'::date + 238), '{}'::text[], 'Révision', 'Réviser les notions sur le vivant : animaux, plantes, corps humain, santé.', null, array['révision'], null),
    (v_class, 36, ('2026-09-01'::date + 245), '{}'::text[], 'Révision', 'Réviser les notions de repérage dans le temps et l''espace.', null, array['révision'], null);

  insert into progression (class_id, matiere, numero, items, pages, mots_exemple) values
    (v_class, 'francais', 1, array['a','i','y','o','u'], '8-9', null),
    (v_class, 'francais', 2, array['e','é','l'], '10-11', array['lit']),
    (v_class, 'francais', 3, array['r','f'], '12-13', array['rat','fée']),
    (v_class, 'francais', 4, array['j','ou'], '14-15', array['jars','loup']),
    (v_class, 'francais', 5, array['v','ch'], '18-19', array['vol','chat']),
    (v_class, 'francais', 6, array['e','s','t','h'], '20-25', array['lettres muettes']),
    (v_class, 'francais', 7, array['p','t'], '26-27', array['poule','tomate']),
    (v_class, 'francais', 8, array['b','d'], '28-29', array['balle','doudou']),
    (v_class, 'francais', 9, array['m','n'], '32-33', array['mouche','nid']),
    (v_class, 'francais', 10, array['z','s'], '34-35', array['zoo','souris']),
    (v_class, 'francais', 11, array['s','è','ê'], '38-39', array['rose','sirène']),
    (v_class, 'francais', 12, array['es','eu','œu'], '40-41', array['les','jeu','œuf']),
    (v_class, 'francais', 13, array['a','d'], '42-47', array['lettres muettes']),
    (v_class, 'francais', 14, array['c','k'], '48-49', array['canard','kimono']),
    (v_class, 'francais', 15, array['q','qu','g','gu'], '50-51', array['coq','queue','goutte','guitare']),
    (v_class, 'francais', 16, array['an','am','en','em'], '54-55', array['maman','vent']),
    (v_class, 'francais', 17, array['on','om','in','im'], '56-57', array['mouton','poussin']),
    (v_class, 'francais', 18, array['oi','oin'], '60-61', array['étoile','point']),
    (v_class, 'francais', 19, array['au','eau'], '62-63', array['taupe','oiseau']),
    (v_class, 'francais', 20, array['b','f','c'], '64-69', array['lettres muettes']),
    (v_class, 'francais', 21, array['ai','ei','err','ess','ett','eil','enn'], '70-71', array['laine','reine','terre']),
    (v_class, 'francais', 22, array['e','et'], '73-74', array['mer','poulet']),
    (v_class, 'francais', 23, array['er','ez','ph'], '78-79', array['rocher','nez','phoque']),
    (v_class, 'francais', 24, array['c','ç','sc'], '81-82', array['glace','garçon','piscine']),
    (v_class, 'francais', 25, array['g','ge'], '86-87', array['girafe','pigeon']),
    (v_class, 'francais', 26, array['gn','ain','ein'], '89-90', array['cigogne','copain','peinture']),
    (v_class, 'francais', 27, array['g','l','p'], '92-97', array['lettres muettes']),
    (v_class, 'francais', 28, array['ier','ieu','ion','ian','ien'], '98-99', array['cahier','chien']),
    (v_class, 'francais', 29, array['x','ti'], '104-105', array['xylophone','addition']),
    (v_class, 'francais', 30, array['y','ay','oy','ey','uy'], '112-113', array['yaourt','crayon']),
    (v_class, 'francais', 31, array['ill','ail','eil','euil','ouil'], '118-119', array['coquille','soleil']),
    (v_class, 'francais', 32, array['w'], '126-127', array['kiwi']),
    (v_class, 'francais', 33, '{}'::text[], '132-135', array['cas particuliers']),
    (v_class, 'francais', 34, '{}'::text[], null, array['révision']),
    (v_class, 'francais', 35, '{}'::text[], null, array['révision']),
    (v_class, 'francais', 36, '{}'::text[], null, array['révision']);

  insert into progression (class_id, matiere, numero, items, pages, mots_exemple) values
    (v_class, 'maths', 1, array['Nombres jusqu’à 10','Repérage dans l’espace'], null, null),
    (v_class, 'maths', 2, array['Décomposer 4 et 5','Tables d’addition : les suivants'], null, null),
    (v_class, 'maths', 3, array['Nombres ordinaux','Les doubles'], null, null),
    (v_class, 'maths', 4, array['Groupements par 5 et par 10','Les presque doubles'], null, null),
    (v_class, 'maths', 5, array['Tables d’addition : sommes inférieures à 10','Ajouter ou soustraire 2'], null, null),
    (v_class, 'maths', 6, array['Problèmes additifs en une étape','Égalisation, parties-tout, transformation'], null, null),
    (v_class, 'maths', 7, array['Problèmes ouverts','Révision période 1'], null, null),
    (v_class, 'maths', 8, array['Représentations d’un même nombre','Ajouter ou soustraire 10'], null, null),
    (v_class, 'maths', 9, array['Nombres entiers jusqu’à 59','Ajouter ou soustraire 1 ou 2'], null, null),
    (v_class, 'maths', 10, array['Compléments à 10','Monnaie'], null, null),
    (v_class, 'maths', 11, array['Comparaison de nombres jusqu’à 99','Soustraire un nombre à 10'], null, null),
    (v_class, 'maths', 12, array['Nombres entiers jusqu’à 79','Doubles des nombres de 1 à 10'], null, null),
    (v_class, 'maths', 13, array['Écriture chiffrée des nombres jusqu’à 99','Doubles des dizaines entières'], null, null),
    (v_class, 'maths', 14, array['Tables d’addition : le passage par 10','Solides','Problèmes additifs (parties-tout, transformation)'], null, null),
    (v_class, 'maths', 15, array['Nombres entiers jusqu’à 100','Complément à la dizaine supérieure'], null, null),
    (v_class, 'maths', 16, array['Tableau des nombres jusqu’à 100','Ajouter un nombre inférieur à 9'], null, null),
    (v_class, 'maths', 17, array['Comparaison de longueurs','Moitié d’un nombre pair de 2 à 20'], null, null),
    (v_class, 'maths', 18, array['Mesure de longueurs par report de l’unité','Ajouter ou soustraire 10'], null, null),
    (v_class, 'maths', 19, array['Unité de mesure : le centimètre','Ajouter ou soustraire 20, 30, … 90'], null, null),
    (v_class, 'maths', 20, array['Repérage sur un quadrillage','Ajouter deux nombres inférieurs à 100'], null, null),
    (v_class, 'maths', 21, array['Problèmes multiplicatifs (recherche du tout, du nombre de parts)','Problèmes additifs (transformation)'], null, null),
    (v_class, 'maths', 22, array['Problèmes ouverts','Révision période 3'], null, null),
    (v_class, 'maths', 23, array['Écriture en lettres des nombres jusqu’à 59','Additions et soustractions avec le matériel de numération'], null, null),
    (v_class, 'maths', 24, array['Nombres ordinaux','Calcul posé : addition'], null, null),
    (v_class, 'maths', 25, array['Ajouter deux nombres inférieurs à 100','Ajouter 9'], null, null),
    (v_class, 'maths', 26, array['Soustraire un nombre < 10 à un nombre entier de dizaines','Unité de mesure : le mètre'], null, null),
    (v_class, 'maths', 27, array['Tables d’addition : presque doubles, passage par 10','Formes planes'], null, null),
    (v_class, 'maths', 28, array['Moitié d’un nombre pair','Tracés à la règle et alignements'], null, null),
    (v_class, 'maths', 29, array['Problèmes additifs en deux étapes','Problèmes multiplicatifs (valeur d’une part)','Déplacements sur un quadrillage'], null, null),
    (v_class, 'maths', 30, array['Révision : ajouter deux nombres < 100','Lecture de l’heure'], null, null),
    (v_class, 'maths', 31, array['Révision : ajouter ou soustraire 20 à 90','Comparaison d’objets selon leur masse'], null, null),
    (v_class, 'maths', 32, array['Révision : tables d’addition','Formes planes'], null, null),
    (v_class, 'maths', 33, array['Ajouter un nombre inférieur à 9','Assemblage de figures planes'], null, null),
    (v_class, 'maths', 34, array['Moitié d’un nombre pair','Tableaux et diagrammes en barres'], null, null),
    (v_class, 'maths', 35, array['Méli-mélo de calculs','Tableaux à double entrée'], null, null),
    (v_class, 'maths', 36, array['Codage du déplacement d’un robot','Problèmes ouverts — types variés','Révision période 5'], null, null);

  insert into emploi_du_temps (class_id, jour, heure_debut, heure_fin, matiere, ordre, couleur, type) values
    (v_class, 'lundi', '08:20', '08:30', 'Accueil dans la cour', 0, '#f3f4f6', 'routine'),
    (v_class, 'mardi', '08:20', '08:30', 'Accueil dans la cour', 1, '#f3f4f6', 'routine'),
    (v_class, 'jeudi', '08:20', '08:30', 'Accueil dans la cour', 2, '#f3f4f6', 'routine'),
    (v_class, 'vendredi', '08:20', '08:30', 'Accueil dans la cour', 3, '#f3f4f6', 'routine'),
    (v_class, 'lundi', '08:30', '08:45', 'Rituels du jour, appel…', 4, '#f3f4f6', 'routine'),
    (v_class, 'mardi', '08:30', '08:45', 'Rituels du jour, appel…', 5, '#f3f4f6', 'routine'),
    (v_class, 'jeudi', '08:30', '08:45', 'Rituels du jour, appel…', 6, '#f3f4f6', 'routine'),
    (v_class, 'vendredi', '08:30', '08:45', 'Rituels du jour, appel…', 7, '#f3f4f6', 'routine'),
    (v_class, 'lundi', '08:45', '09:15', 'Appropriation des graphèmes', 8, '#dbeafe', 'cours'),
    (v_class, 'mardi', '08:45', '09:15', 'Appropriation des graphèmes', 9, '#dbeafe', 'cours'),
    (v_class, 'jeudi', '08:45', '09:15', 'Appropriation des graphèmes', 10, '#dbeafe', 'cours'),
    (v_class, 'vendredi', '08:45', '09:15', 'Appropriation des graphèmes', 11, '#dbeafe', 'cours'),
    (v_class, 'lundi', '09:15', '09:45', 'Écriture', 12, '#dbeafe', 'cours'),
    (v_class, 'mardi', '09:15', '09:45', 'Phonologie', 13, '#dbeafe', 'cours'),
    (v_class, 'jeudi', '09:15', '09:45', 'Écriture', 14, '#dbeafe', 'cours'),
    (v_class, 'vendredi', '09:15', '09:45', 'Phonologie', 15, '#dbeafe', 'cours'),
    (v_class, 'lundi', '09:45', '10:00', 'Vocabulaire', 16, '#dbeafe', 'cours'),
    (v_class, 'mardi', '09:45', '10:00', 'Lecture-écriture', 17, '#dbeafe', 'cours'),
    (v_class, 'jeudi', '09:45', '10:00', 'Vocabulaire', 18, '#dbeafe', 'cours'),
    (v_class, 'vendredi', '09:45', '10:00', 'Lecture-écriture', 19, '#dbeafe', 'cours'),
    (v_class, 'lundi', '10:00', '10:15', 'Récréation', 20, '#f3f4f6', 'routine'),
    (v_class, 'mardi', '10:00', '10:15', 'Récréation', 21, '#f3f4f6', 'routine'),
    (v_class, 'jeudi', '10:00', '10:15', 'Récréation', 22, '#f3f4f6', 'routine'),
    (v_class, 'vendredi', '10:00', '10:15', 'Récréation', 23, '#f3f4f6', 'routine'),
    (v_class, 'lundi', '10:15', '10:30', 'Calcul mental', 24, '#fbcfe8', 'cours'),
    (v_class, 'mardi', '10:15', '10:30', 'Calcul mental', 25, '#fbcfe8', 'cours'),
    (v_class, 'jeudi', '10:15', '10:30', 'Calcul mental', 26, '#fbcfe8', 'cours'),
    (v_class, 'vendredi', '10:15', '10:30', 'Calcul mental', 27, '#fbcfe8', 'cours'),
    (v_class, 'lundi', '10:30', '11:30', 'Mathématiques', 28, '#fbcfe8', 'cours'),
    (v_class, 'mardi', '10:30', '11:30', 'Mathématiques', 29, '#fbcfe8', 'cours'),
    (v_class, 'jeudi', '10:30', '11:30', 'Mathématiques', 30, '#fbcfe8', 'cours'),
    (v_class, 'vendredi', '10:30', '11:30', 'Mathématiques', 31, '#fbcfe8', 'cours'),
    (v_class, 'lundi', '11:30', '13:20', 'Pause déjeuner / APC', 32, '#f3f4f6', 'routine'),
    (v_class, 'mardi', '11:30', '13:20', 'Pause déjeuner / APC', 33, '#f3f4f6', 'routine'),
    (v_class, 'jeudi', '11:30', '13:20', 'Pause déjeuner / APC', 34, '#f3f4f6', 'routine'),
    (v_class, 'vendredi', '11:30', '13:20', 'Pause déjeuner / APC', 35, '#f3f4f6', 'routine'),
    (v_class, 'lundi', '13:20', '13:30', 'Accueil dans la cour', 36, '#f3f4f6', 'routine'),
    (v_class, 'mardi', '13:20', '13:30', 'Accueil dans la cour', 37, '#f3f4f6', 'routine'),
    (v_class, 'jeudi', '13:20', '13:30', 'Accueil dans la cour', 38, '#f3f4f6', 'routine'),
    (v_class, 'vendredi', '13:20', '13:30', 'Accueil dans la cour', 39, '#f3f4f6', 'routine'),
    (v_class, 'lundi', '13:30', '13:45', 'Chut je lis', 40, null, 'cours'),
    (v_class, 'mardi', '13:30', '13:45', 'Chut je lis', 41, null, 'cours'),
    (v_class, 'jeudi', '13:30', '13:45', 'Chut je lis', 42, null, 'cours'),
    (v_class, 'vendredi', '13:30', '13:45', 'Chut je lis', 43, null, 'cours'),
    (v_class, 'lundi', '13:45', '14:15', 'Lecture compréhension', 44, null, 'cours'),
    (v_class, 'mardi', '13:45', '14:15', 'Production d''écrits', 45, null, 'cours'),
    (v_class, 'jeudi', '13:45', '14:15', 'Lecture compréhension', 46, null, 'cours'),
    (v_class, 'vendredi', '13:45', '14:15', 'Production d''écrits', 47, null, 'cours'),
    (v_class, 'lundi', '14:15', '14:45', 'Histoire géographie', 48, null, 'cours'),
    (v_class, 'mardi', '14:15', '14:45', 'Arts visuels', 49, '#ddd6fe', 'cours'),
    (v_class, 'jeudi', '14:15', '14:45', 'Sciences et technologie', 50, null, 'cours'),
    (v_class, 'vendredi', '14:15', '14:45', 'Anglais', 51, '#fed7aa', 'cours'),
    (v_class, 'lundi', '14:45', '15:00', 'Écriture', 52, '#dbeafe', 'cours'),
    (v_class, 'mardi', '14:45', '15:00', 'Vocabulaire', 53, '#dbeafe', 'cours'),
    (v_class, 'jeudi', '14:45', '15:00', 'Écriture', 54, '#dbeafe', 'cours'),
    (v_class, 'vendredi', '14:45', '15:00', 'Vocabulaire', 55, '#dbeafe', 'cours'),
    (v_class, 'lundi', '15:00', '15:15', 'Récréation', 56, '#f3f4f6', 'routine'),
    (v_class, 'mardi', '15:00', '15:15', 'Récréation', 57, '#f3f4f6', 'routine'),
    (v_class, 'jeudi', '15:00', '15:15', 'Récréation', 58, '#f3f4f6', 'routine'),
    (v_class, 'vendredi', '15:00', '15:15', 'Récréation', 59, '#f3f4f6', 'routine'),
    (v_class, 'lundi', '15:15', '15:45', 'EPS', 60, '#fef08a', 'cours'),
    (v_class, 'mardi', '15:15', '15:45', 'Anglais', 61, '#fed7aa', 'cours'),
    (v_class, 'jeudi', '15:15', '15:45', 'EPS', 62, '#fef08a', 'cours'),
    (v_class, 'vendredi', '15:15', '15:45', 'Arts visuels', 63, '#ddd6fe', 'cours'),
    (v_class, 'lundi', '15:45', '16:15', 'EPS', 64, '#fef08a', 'cours'),
    (v_class, 'mardi', '15:45', '16:15', 'EMC', 65, null, 'cours'),
    (v_class, 'jeudi', '15:45', '16:15', 'EPS', 66, '#fef08a', 'cours'),
    (v_class, 'vendredi', '15:45', '16:15', 'EMC', 67, null, 'cours'),
    (v_class, 'lundi', '16:15', '16:30', 'Bilan de la journée, devoirs, cartable', 68, '#f3f4f6', 'routine'),
    (v_class, 'mardi', '16:15', '16:30', 'Bilan de la journée, cartable', 69, '#f3f4f6', 'routine'),
    (v_class, 'jeudi', '16:15', '16:30', 'Bilan de la journée, cartable', 70, '#f3f4f6', 'routine'),
    (v_class, 'vendredi', '16:15', '16:30', 'Bilan de la journée, cartable', 71, '#f3f4f6', 'routine');

  raise notice 'Classe creee : %', v_class;
end $$;
